### ISSUE TITLE
ImportError: No module named functools_lru_cache

### ISSUE THREAD

**Issue by szczys** [greatscottgadgets/libgreat#2]
I needed an additional package installed for greatfet to run. Running `greatfet info` throws this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/greatfet", line 6, in &lt;module&gt;
    from greatfet.commands.gf import main
  File "/usr/local/lib/python2.7/dist-packages/greatfet/__init__.py", line 3, in &lt;module&gt;
    from .greatfet import GreatFET
  File "/usr/local/lib/python2.7/dist-packages/greatfet/greatfet.py", line 5, in &lt;module&gt;
    from .board import GreatFETBoard
  File "/usr/local/lib/python2.7/dist-packages/greatfet/board.py", line 12, in &lt;module&gt;
    from pygreat.board import GreatBoard
  File "/usr/local/lib/python2.7/dist-packages/pygreat/board.py", line 15, in &lt;module&gt;
    from pygreat.comms import CommsBackend
  File "/usr/local/lib/python2.7/dist-packages/pygreat/comms.py", line 21, in &lt;module&gt;
    from backports.functools_lru_cache import lru_cache as memoize_with_lru_cache
ImportError: No module named functools_lru_cache
```

Workaround is to install:
`sudo apt install python-backports.functools-lru-cache`

Linux 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by szczys** [comment]
If recommendation is to use Python3 (as discussed in #1 ) then this is erroneous.

**Comment by ktemkin** [comment]
This is still an odd error; as `pip` should automatically pull that dependency down. Our metadata has it marked as as requirement:

```python
install_requires=['pyusb', 'future', 'backports.functools_lru_cache'],
```
(from https://github.com/greatscottgadgets/libgreat/blob/master/host/setup.py#L35). 

I'm re-opening this to remind myself to test this some more.

**Comment by mossmann** [comment]
I accidentally opened a duplicate issue which has further discussion:
https://github.com/greatscottgadgets/greatfet/issues/251
